# Generated by Django 6.1.1 on 2026-09-23 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Article Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(help_text='Concise summary for preview cards, social shares, and SEO.', verbose_name='Short Summary')),
                ('content', models.TextField(help_text='Full article body (Supports rich HTML / Markdown formatted text).', verbose_name='Article Content')),
                ('author', models.CharField(default='K Satyanarayana Chary (@sathya)', max_length=120, verbose_name='Author')),
                ('category', models.CharField(default='Engineering', max_length=80, verbose_name='Category / Domain')),
                ('tags', models.CharField(default='Spring Boot, React Native, AWS', help_text='Comma-separated tags (e.g. Java, AWS, Mobile)', max_length=200, verbose_name='Tags')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/%Y/%m/', verbose_name='Cover Image Upload')),
                ('image_url', models.URLField(blank=True, help_text='Optional fallback image URL if not uploading file.', null=True, verbose_name='Image URL Fallback')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Total Views')),
                ('read_time', models.CharField(default='5 min read', max_length=40, verbose_name='Estimated Read Time')),
                ('sources', models.TextField(blank=True, help_text='References, documentation links, citations, or GitHub repositories (one per line or comma-separated).', verbose_name='References & Sources')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published Status')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date & Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Blog Article',
                'verbose_name_plural': 'Blog Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Sender Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Sender Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject / Inquiry Type')),
                ('message', models.TextField(verbose_name='Transmission Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Mark as Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
